# Generated by Django 5.2.3 on 2025-08-25 04:02

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='শিরোনাম')),
                ('ad_image', models.ImageField(upload_to='ads/', verbose_name='বিজ্ঞাপনের ছবি')),
                ('ad_url', models.URLField(verbose_name='বিজ্ঞাপনের লিংক')),
                ('ad_location', models.CharField(choices=[('top_banner', 'শীর্ষ ব্যানার'), ('sidebar', 'সাইডবার'), ('bottom_banner', 'নিচের ব্যানার'), ('in_article', 'নিবন্ধের মধ্যে'), ('popup', 'পপআপ')], max_length=20, verbose_name='বিজ্ঞাপনের অবস্থান')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('start_date', models.DateTimeField(verbose_name='শুরুর তারিখ')),
                ('end_date', models.DateTimeField(verbose_name='শেষ তারিখ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'বিজ্ঞাপন',
                'verbose_name_plural': 'বিজ্ঞাপনসমূহ',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='নাম')),
                ('slug', models.SlugField(unique=True, verbose_name='স্লাগ')),
            ],
            options={
                'verbose_name': 'ট্যাগ',
                'verbose_name_plural': 'ট্যাগসমূহ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='নাম')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='স্লাগ')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.category', verbose_name='প্যারেন্ট ক্যাটেগরি')),
            ],
            options={
                'verbose_name': 'ক্যাটেগরি',
                'verbose_name_plural': 'ক্যাটেগরিসমূহ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish_date', verbose_name='স্লাগ')),
                ('image', models.ImageField(upload_to='articles/%Y/%m/%d/', verbose_name='ছবি')),
                ('image_caption', models.CharField(blank=True, max_length=200, verbose_name='ছবির ক্যাপশন')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='বিষয়বস্তু')),
                ('summary', models.TextField(max_length=500, verbose_name='সারসংক্ষেপ')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='প্রকাশের তারিখ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='আপডেটের তারিখ')),
                ('status', models.CharField(choices=[('draft', 'খসড়া'), ('published', 'প্রকাশিত'), ('archived', 'সংরক্ষিত')], default='draft', max_length=10, verbose_name='অবস্থা')),
                ('is_breaking', models.BooleanField(default=False, verbose_name='জরুরি সংবাদ')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='দেখা হয়েছে')),
                ('featured', models.BooleanField(default=False, verbose_name='ফিচারড')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='লেখক')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='ট্যাগসমূহ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.category', verbose_name='ক্যাটেগরি')),
            ],
            options={
                'verbose_name': 'নিবন্ধ',
                'verbose_name_plural': 'নিবন্ধসমূহ',
                'ordering': ['-publish_date'],
                'get_latest_by': 'publish_date',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='মন্তব্য')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('active', models.BooleanField(default=False, verbose_name='সক্রিয়')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.article', verbose_name='নিবন্ধ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'মন্তব্য',
                'verbose_name_plural': 'মন্তব্যসমূহ',
                'ordering': ['-created_date'],
            },
        ),
    ]
