# Generated by Django 4.2.11 on 2026-04-23 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_position', models.PositiveIntegerField()),
                ('column_position', models.PositiveIntegerField()),
                ('raw_input', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(choices=[('blank', 'Blank'), ('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('error', 'Error')], default='blank', max_length=16)),
                ('computed_value', models.JSONField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField(default=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spreadsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='sheets.spreadsheet')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SheetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=16)),
                ('data_type', models.CharField(default='text', max_length=16)),
                ('width', models.PositiveIntegerField(default=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spreadsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='sheets.spreadsheet')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CellDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on_row_position', models.PositiveIntegerField()),
                ('depends_on_column_position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='sheets.cell')),
                ('spreadsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='sheets.spreadsheet')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sheets.sheetcolumn'),
        ),
        migrations.AddField(
            model_name='cell',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sheets.sheetrow'),
        ),
        migrations.AddField(
            model_name='cell',
            name='spreadsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sheets.spreadsheet'),
        ),
        migrations.AddConstraint(
            model_name='spreadsheet',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_sheet_slug_per_owner'),
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(fields=['spreadsheet', 'position'], name='sheets_shee_spreads_ea2ede_idx'),
        ),
        migrations.AddConstraint(
            model_name='sheetrow',
            constraint=models.UniqueConstraint(fields=('spreadsheet', 'position'), name='uniq_sheet_row_position'),
        ),
        migrations.AddIndex(
            model_name='sheetcolumn',
            index=models.Index(fields=['spreadsheet', 'position'], name='sheets_shee_spreads_6f3d91_idx'),
        ),
        migrations.AddConstraint(
            model_name='sheetcolumn',
            constraint=models.UniqueConstraint(fields=('spreadsheet', 'position'), name='uniq_sheet_column_position'),
        ),
        migrations.AddIndex(
            model_name='celldependency',
            index=models.Index(fields=['spreadsheet', 'depends_on_row_position', 'depends_on_column_position'], name='sheets_cell_spreads_d7a057_idx'),
        ),
        migrations.AddIndex(
            model_name='celldependency',
            index=models.Index(fields=['spreadsheet', 'source_cell'], name='sheets_cell_spreads_068254_idx'),
        ),
        migrations.AddConstraint(
            model_name='celldependency',
            constraint=models.UniqueConstraint(fields=('source_cell', 'depends_on_row_position', 'depends_on_column_position'), name='uniq_cell_dependency'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['spreadsheet', 'row_position', 'column_position'], name='sheets_cell_spreads_896c79_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['spreadsheet', 'column_position', 'row_position'], name='sheets_cell_spreads_588de9_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['spreadsheet', 'updated_at'], name='sheets_cell_spreads_dfeab0_idx'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('spreadsheet', 'row', 'column'), name='uniq_cell_row_column'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('spreadsheet', 'row_position', 'column_position'), name='uniq_cell_position_in_sheet'),
        ),
    ]
